#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'psy-froggy-bot'
primary_region = 'arn'

[mounts]
  source='data'
  destination='/data'
  processes = ['app']

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[checks]
  [checks.my_health_check]
    type = 'http'
    interval = '15s'
    timeout = '10s'
    grace_period = '30s'
    method = 'get'
    path = '/status'

    [checks.my_health_check.headers]
      Content-Type = 'application/json'
