# fly.toml app configuration file generated for psy-froggy-bot on 2025-05-26T18:10:39Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'psy-froggy-bot'
primary_region = 'arn'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256


[checks]
  [checks.my_health_check]
    grace_period = "30s"
    interval = "15s"
    method = "get"
    path = "/status"
    # port = 5500
    timeout = "10s"
    type = "http"
    [checks.my_health_check.headers]
      Content-Type = "application/json"
      # Authorization = "super-secret"
