name: Deploy to Digital Ocean

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Run tests (если есть)
        run: bun test --if-present

      - name: Deploy to Digital Ocean
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          port: ${{ secrets.DO_PORT }}
          script: |
            set -euo pipefail
            echo "🚀 Starting deployment..."

            # Переход в директорию проекта
            cd /var/www/psy_froggy_bot

            # Остановка текущего приложения
            pm2 stop psy_froggy_bot || true

            # Backup базы данных
            sudo cp /var/www/databases/psy_froggy_bot/froggy.db /var/www/databases/psy_froggy_bot/froggy.db.backup.$(date +%Y%m%d_%H%M%S) || true

            # Обновление кода
            git fetch origin
            git reset --hard origin/main

            # Установка зависимостей
            bun install --frozen-lockfile

            # Запуск миграций
            bun run knex migrate:latest --knexfile knexfile.cjs

            # Перезапуск приложения через PM2
            pm2 restart psy_froggy_bot || pm2 start ecosystem.config.js --name psy_froggy_bot

            # Перезагрузка Caddy (если нужно)
            sudo systemctl reload caddy

            echo "✅ Deployment completed!"

      - name: Notify on success
        if: success()
        run: |
          echo "🎉 Deployment successful!"

      - name: Notify on failure
        if: failure()
        run: |
          echo "❌ Deployment failed!"
